- user: av
  sudo: no
  hosts: all
  gather_facts: no
  tasks:
  - git:
      repo: git@github.com:savonarola/pulse-meter-demo.git
      dest: pulse-meter.rubybox.ru
      accept_hostkey: yes
      branch: ansible
  - shell: bundle install --deployment chdir=pulse-meter.rubybox.ru

- user: av
  sudo: yes
  hosts: all
  gather_facts: no
  tasks:
  - file:
      src: /home/av/pulse-meter.rubybox.ru/deploy/pulse-meter-demo.service
      dest: /etc/systemd/system/pulse-meter-demo.service
      state: link

